import { type FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Eye, EyeOff, ArrowLeft } from "lucide-react";
import { supabase } from "../lib/supabase";
import { Brand } from "../components/Brand";

export function Login(){
 const nav=useNavigate(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setError("");setLoading(true);const {error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error){setError("Sign-in details could not be verified. Please check them and try again.");return}nav("/app");}
 return <div className="min-h-screen bg-sand px-5 py-8"><div className="mx-auto max-w-md"><Link to="/" className="mb-12 inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={16}/>Back</Link><Brand/><div className="mt-10 rounded-[2rem] bg-white p-6 shadow-soft sm:p-8"><h1 className="text-2xl font-semibold">Welcome back</h1><p className="mt-2 text-sm text-slate-500">Sign in to your fictional NONa+ account.</p><form onSubmit={submit} className="mt-7 space-y-5"><label className="block text-sm font-medium">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 bg-sand px-4 py-3.5 outline-none focus:border-moss"/></label><label className="block text-sm font-medium">Password<div className="relative mt-2"><input required type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-xl border border-black/10 bg-sand px-4 py-3.5 pr-12 outline-none focus:border-moss"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-3.5 text-slate-400" aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label>{error&&<div role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button disabled={loading} className="w-full rounded-xl bg-ink py-3.5 text-sm font-semibold text-white">{loading?"Signing in…":"Sign In"}</button></form><div className="mt-5 flex justify-between text-sm"><Link to="/forgot-password" className="text-moss underline-offset-4 hover:underline">Forgot password?</Link><Link to="/register" className="font-semibold">Create Account</Link></div></div></div></div>
}
