import { Eye, EyeOff, ArrowUpRight, ArrowDownLeft, Plus, Minus, CreditCard } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../lib/auth";
import { supabase } from "../lib/supabase";
import { Card, Money, PageTitle } from "../components/ui";
import type { Account, Transaction } from "../lib/types";

export function Overview(){
 const {user,profile}=useAuth(); const [account,setAccount]=useState<Account|null>(null); const [tx,setTx]=useState<Transaction[]>([]); const [hidden,setHidden]=useState(false);
 useEffect(()=>{if(!user)return; (async()=>{const {data:a}=await supabase.from("accounts").select("*").eq("user_id",user.id).maybeSingle();setAccount(a as Account|null);if(a){const {data:t}=await supabase.from("transactions").select("*").eq("account_id",a.id).order("created_at",{ascending:false}).limit(5);setTx((t??[]) as Transaction[])}})()},[user]);
 return <><PageTitle eyebrow="NONa+ Environment" title={`Good to see you, ${profile?.first_name ?? "there"}.`}><Link to="/app/transfers" className="rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white">Transfer money</Link></PageTitle>
 <div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><Card className="overflow-hidden bg-ink text-white dark:bg-moss"><div className="flex items-start justify-between"><div><div className="text-sm text-white/55">M.&T Everyday Checking · {account?.masked_number ?? "**** 4821"}</div><div className="mt-3 text-4xl font-semibold tracking-tight">{hidden?"••••••":`$${(account?.available_balance??2500000.5).toLocaleString("en-US",{minimumFractionDigits:2})}`}</div><div className="mt-2 text-xs text-white/45">Available balance</div></div><button onClick={()=>setHidden(!hidden)} aria-label={hidden?"Show balance":"Hide balance"} className="rounded-xl bg-white/10 p-2">{hidden?<Eye size={18}/>:<EyeOff size={18}/>}</button></div><div className="mt-10 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><div className="text-xs text-white/45">Current balance</div><div className="mt-1 font-semibold">{hidden?"••••":`$${(account?.current_balance??2500000.5).toLocaleString()}`}</div></div><div className="rounded-2xl bg-white/10 p-4"><div className="text-xs text-white/45">Pending</div><div className="mt-1 font-semibold">{hidden?"••••":`$${(account?.pending_balance??255).toLocaleString()}`}</div></div></div></Card>
 <Card><div className="flex items-center justify-between"><h2 className="font-semibold">Quick actions</h2><span className="text-xs text-slate-400">Fictional only</span></div><div className="mt-5 grid grid-cols-2 gap-3">{[[ArrowUpRight,"Transfer","/app/transfers"],[Plus,"Deposit","/app/deposit"],[Minus,"Withdraw","/app/withdraw"],[CreditCard,"Cards","/app/cards"]].map(([I,l,to]:any)=><Link key={l} to={to} className="rounded-2xl border border-black/5 p-4 transition hover:-translate-y-0.5 hover:shadow-md"><I size={19}/><div className="mt-5 text-sm font-semibold">{l}</div></Link>)}</div></Card></div>
 <Card className="mt-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent NONa+ activity</h2><Link to="/app/transactions" className="text-sm font-semibold text-moss">View all</Link></div><div className="mt-4 divide-y divide-black/5">{tx.length?tx.map(t=><div key={t.id} className="flex items-center justify-between py-4"><div><div className="text-sm font-medium">{t.description}</div><div className="mt-1 text-xs text-slate-400">{new Date(t.created_at).toLocaleDateString()} · {t.status}</div></div><div className={t.amount>=0?"text-emerald-700":"text-ink"}><Money value={t.amount} sign/></div></div>):<div className="py-10 text-center text-sm text-slate-400">No NONa+ transactions yet.</div>}</div></Card>
 </>;
}
