import { type FormEvent, useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { useAuth } from "../lib/auth";
import { Button, Card, Money, PageTitle } from "../components/ui";
export function Transfer({kind="transfer"}:{kind?: "transfer"|"deposit"|"withdrawal"}){const {user}=useAuth();const nav=useNavigate();const [form,setForm]=useState({name:"",account:"",amount:"",description:""});const [confirm,setConfirm]=useState(false);const [error,setError]=useState("");const [loading,setLoading]=useState(false);const labels={transfer:["Transfer","Recipient name","Recipient account"],deposit:["Deposit","Source","Description"],withdrawal:["Withdraw","Destination","Description"]};const [title,a,b]=labels[kind];
async function submit(e:FormEvent){e.preventDefault();setError("");const amount=Number(form.amount);if(!Number.isFinite(amount)||amount<=0)return setError("Enter a valid positive amount.");if(kind==="transfer"&&!form.account)return setError("Enter the fictional recipient account.");setConfirm(true)}
async function complete(){if(!user)return;setLoading(true);const {data,error}=await supabase.rpc("perform_nona_transaction",{p_kind:kind,p_amount:Number(form.amount),p_description:form.description||`${title} NONa+ activity`,p_counterparty:form.name||null,p_recipient_account:form.account||null});setLoading(false);if(error){setError(error.message.includes("INSUFFICIENT")?"Insufficient fictional balance.": "The NONa+ transaction could not be completed.");setConfirm(false);return}nav("/app/transactions")}
return <><PageTitle eyebrow="NONa+ Transaction" title={title}/>{confirm?<Card className="mx-auto max-w-xl"><div className="text-sm text-slate-400">Confirmation</div><h2 className="mt-2 text-2xl font-semibold">Review {title.toLowerCase()}</h2><div className="mt-7 space-y-3 rounded-2xl bg-sand p-5"><div className="flex justify-between"><span className="text-slate-500">Amount</span><strong><Money value={Number(form.amount)}/></strong></div>{form.name&&<div className="flex justify-between"><span className="text-slate-500">{a}</span><strong>{form.name}</strong></div>}{form.account&&<div className="flex justify-between"><span className="text-slate-500">{b}</span><strong>{form.account}</strong></div>}</div><div className="mt-6 flex gap-3"><Button variant="light" onClick={()=>setConfirm(false)}>Back</Button><Button disabled={loading} onClick={complete}>{loading?"Processing…":"Confirm Transaction"}</Button></div></Card>:<Card className="mx-auto max-w-xl"><form onSubmit={submit} className="space-y-5">{kind!=="deposit"&&<label className="block text-sm font-medium">{a}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-xl border border-black/10 bg-sand px-4 py-3.5"/></label>}{kind==="transfer"&&<label className="block text-sm font-medium">{b}<input required value={form.account} onChange={e=>setForm({...form,account:e.target.value})} placeholder="**** 4821" className="mt-2 w-full rounded-xl border border-black/10 bg-sand px-4 py-3.5"/></label>}<label className="block text-sm font-medium">Amount<input required inputMode="decimal" min="0.01" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="mt-2 w-full rounded-xl border border-black/10 bg-sand px-4 py-3.5"/></label><label className="block text-sm font-medium">Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-2 w-full rounded-xl border border-black/10 bg-sand px-4 py-3.5"/></label>{error&&<div role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<Button type="submit">{title}</Button></form></Card>}</>}
